"""The declarative base every model inherits from.

The naming convention is the important part. Left to itself, PostgreSQL invents
names for indexes and constraints, and those names differ between the database
Alembic autogenerated against and the one it later runs on. A migration that
says `DROP CONSTRAINT ck_hotel_a1b2c3` then fails in production.

Fixing the convention here means every constraint has a deterministic name
derived from its table and columns, so `downgrade()` can always name what it
needs to drop. This must be set before the first migration — changing it later
means renaming every constraint in a live database.
"""

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base. Import models before running Alembic autogenerate, or
    it will cheerfully generate a migration that drops every table it cannot
    see."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
