"""Idempotency keys for money and inventory mutations (invariant #5).

**The problem.** Every one of these happens routinely:

- WhatsApp redelivers a webhook because our 200 was slow.
- A payment gateway retries a callback it thinks failed.
- An operator double-clicks "confirm".
- A network blip makes a client retry a request that actually succeeded.

Without protection each of these can produce a second booking, a second charge,
or a second ledger entry. Retrofitting idempotency after the first double-charge
is expensive in more than engineering time.

**The mechanism.** The caller supplies a key that identifies the *intent*, not
the attempt — a WhatsApp message id, a gateway event id, a UUID generated by the
console when the operator opens the form. We insert that key with a unique
constraint. The insert either wins (this is the first attempt: do the work) or
loses (this is a replay: return what the first attempt produced).

The database's unique index is what makes this correct under concurrency. Two
simultaneous requests cannot both win, because the second blocks on the index
until the first commits and then sees the conflict. No application-level check
can promise that.
"""

import uuid
from collections.abc import Awaitable, Callable
from dataclasses import dataclass

from sqlalchemy import String, UniqueConstraint, select
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import Mapped, mapped_column

from hotelagent.db.base import Base
from hotelagent.db.mixins import IdMixin, TimestampMixin


class IdempotencyKey(Base, IdMixin, TimestampMixin):
    """One row per intent. The unique constraint is the whole mechanism."""

    __tablename__ = "idempotency_key"

    # Scope namespaces the key, so a WhatsApp message id and a payment gateway
    # event id can never collide even if the strings match.
    scope: Mapped[str] = mapped_column(String(64), nullable=False)
    key: Mapped[str] = mapped_column(String(255), nullable=False)

    # What the first attempt produced, so a replay can return the same answer
    # instead of an error.
    resource_type: Mapped[str | None] = mapped_column(String(64))
    resource_id: Mapped[uuid.UUID | None] = mapped_column()

    __table_args__ = (UniqueConstraint("scope", "key", name="uq_idempotency_key_scope_key"),)


@dataclass(frozen=True)
class IdempotentResult:
    """The outcome of a guarded mutation."""

    resource_id: uuid.UUID | None
    is_replay: bool
    """True when this key had already been used — the work was not run again."""


async def run_once(
    session: AsyncSession,
    *,
    scope: str,
    key: str,
    operation: Callable[[], Awaitable[uuid.UUID]],
    resource_type: str | None = None,
) -> IdempotentResult:
    """Run `operation` at most once for a given (scope, key).

    On the first call the operation runs and its resource id is recorded. On
    any later call with the same key the operation is **not** run, and the
    originally produced resource id is returned.

    The claim and the work share the caller's transaction deliberately: if the
    operation raises, the key insert rolls back with it, so a genuine failure
    can be retried rather than being permanently poisoned by a claimed key.
    """
    claim = (
        pg_insert(IdempotencyKey)
        .values(scope=scope, key=key, resource_type=resource_type)
        .on_conflict_do_nothing(index_elements=["scope", "key"])
        .returning(IdempotencyKey.id)
    )
    claimed_id = (await session.execute(claim)).scalar_one_or_none()

    if claimed_id is None:
        # Someone got here first. Return what they produced.
        existing = await session.scalar(
            select(IdempotencyKey).where(IdempotencyKey.scope == scope, IdempotencyKey.key == key)
        )
        resource_id = existing.resource_id if existing is not None else None
        return IdempotentResult(resource_id=resource_id, is_replay=True)

    resource_id = await operation()

    record = await session.get(IdempotencyKey, claimed_id)
    if record is not None:
        record.resource_id = resource_id
    await session.flush()

    return IdempotentResult(resource_id=resource_id, is_replay=False)
