"""city and hotel

The first migration. Written by hand rather than autogenerated, because the
first one establishes conventions every later migration copies — and because
autogenerate does not get PostgreSQL enum types right (see `downgrade`).

Revision ID: 0001
Revises:
Create Date: 2026-08-12
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# create_type=False stops SQLAlchemy emitting CREATE TYPE implicitly as part of
# create_table. We create and drop them explicitly instead, so both directions
# are symmetric and readable.
integration_tier = postgresql.ENUM(
    "live", "bot", "manual", name="integration_tier", create_type=False
)
verification_status = postgresql.ENUM(
    "pending", "verified", "rejected", "suspended", name="verification_status", create_type=False
)


def upgrade() -> None:
    bind = op.get_bind()
    integration_tier.create(bind, checkfirst=True)
    verification_status.create(bind, checkfirst=True)

    op.create_table(
        "city",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=120), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("active_languages", postgresql.JSONB(), nullable=False),
        sa.Column("config", postgresql.JSONB(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_city")),
        sa.UniqueConstraint("slug", name=op.f("uq_city_slug")),
    )

    op.create_table(
        "hotel",
        sa.Column("id", sa.Uuid(), nullable=False),
        # Invariant #1: the tenancy key, present from the very first migration.
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("reception_phone", sa.String(length=32), nullable=True),
        sa.Column("integration_tier", integration_tier, nullable=False),
        sa.Column("verification_status", verification_status, nullable=False),
        sa.Column("commission_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("trust_score", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("policies", postgresql.JSONB(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hotel")),
        sa.ForeignKeyConstraint(
            ["city_id"], ["city.id"], name=op.f("fk_hotel_city_id_city"), ondelete="RESTRICT"
        ),
        sa.CheckConstraint(
            "commission_rate >= 0 AND commission_rate <= 100",
            name=op.f("ck_hotel_commission_rate_is_a_percentage"),
        ),
    )
    op.create_index(op.f("ix_hotel_city_id"), "hotel", ["city_id"])


def downgrade() -> None:
    """Every migration has a working downgrade, and this one is tested.

    Note the ordering and the enum drops. `drop_table` does **not** remove a
    PostgreSQL enum type — the type is a first-class database object that
    outlives the column using it. Forget these two lines and the downgrade
    "succeeds" while leaving the types behind, so the next `upgrade` fails with
    "type already exists". That is the single most common broken downgrade in
    a Postgres codebase.
    """
    op.drop_index(op.f("ix_hotel_city_id"), table_name="hotel")
    op.drop_table("hotel")
    op.drop_table("city")

    bind = op.get_bind()
    verification_status.drop(bind, checkfirst=True)
    integration_tier.drop(bind, checkfirst=True)
